before-script:
  stage: build
  script:
    - cd frontend
    - npm i
    - cd ../backend
    - yarn install

build-job:
  stage: build
  script:
    - cd frontend
    - npm run build
    - cd ../backend
    - yarn build

test-job1:
  stage: test
  script:
    - echo "Testes executados"

